import type { ProcessedGeographyBundle } from "@/types";

/** Preprocessed runtime geography bundle. Generated by scripts/geography (T021+). */
export const geographyBundle: ProcessedGeographyBundle = {
  version: "0",
  features: [],
};
